FROM php:8.2-fpm

RUN apt-get update && apt-get install -y

RUN apt-get install -y --no-install-recommends \
        openssh-client \
        git \
        zlib1g-dev \
        libxml2-dev \
        libzip-dev \
        libpq-dev \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
        libxslt1-dev \
        libonig-dev \
        nano \
    && docker-php-ext-install \
        zip \
        intl \
        pdo \
        mbstring \
        mysqli \
        pdo_mysql \
        opcache \
        xsl \
        bcmath

RUN docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
    && docker-php-ext-install pgsql pdo_pgsql

# BC Math
RUN docker-php-ext-install bcmath

# RUN docker-php-ext-enable intl mbstring zip

# Install GD
RUN docker-php-ext-configure gd --with-jpeg --with-freetype
#    --enable-gd-native-ttf

RUN docker-php-ext-install -j$(nproc) gd
#RUN docker-php-ext-enable gd

# Install Composer !
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php -r "if (hash_file('sha384', 'composer-setup.php') === 'dac665fdc30fdd8ec78b38b9800061b4150413ff2e3b6f88543c636f7cd84f6db9189d43a81e5503cda447da73c7e5b6') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
RUN php composer-setup.php
RUN php -r "unlink('composer-setup.php');"
RUN mv composer.phar /usr/local/bin/composer

# Install Node
ENV NODE_VERSION=20.11.0
RUN apt install -y curl
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash
ENV NVM_DIR=/root/.nvm
RUN . "$NVM_DIR/nvm.sh" && nvm install ${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" && nvm use v${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" && nvm alias default v${NODE_VERSION}
ENV PATH="/root/.nvm/versions/node/v${NODE_VERSION}/bin/:${PATH}"
RUN node --version
RUN npm --version

# Install Symfony
RUN curl -1sLf 'https://dl.cloudsmith.io/public/symfony/stable/setup.deb.sh' | bash
RUN apt install symfony-cli
#RUN mv /root/.symfony/bin/symfony /usr/local/bin/symfony

# Set the default directory inside the container
WORKDIR /var/www/symfony

RUN chmod 755 /var/www/symfony
RUN chown www-data:www-data /var/www/symfony

# Github
RUN git config --global user.email "davidbermudez@jerez.es"
RUN git config --global user.name "davidbermudez"
RUN git config --global credential.helper 'cache --timeout 3600'
