services:

  php:
    container_name: symfony7_php
    build:
      context: .
      dockerfile: Dockerfile-php
    volumes:
      - files:/var/www/symfony/
      - ./build/php/:/usr/local/etc/php/
    networks:
      docker_net:
        ipv4_address: 172.20.0.2


  nginx:
    container_name: symfony7_nginx
    depends_on:
      - php
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - 5555:80
      - 5553:443
    volumes:
      - files:/var/www/symfony/
      - ./build/nginx/conf.d:/etc/nginx/conf.d/
    networks:
      docker_net:
        ipv4_address: 172.20.0.10

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    networks:
      docker_net:
        ipv4_address: 172.20.0.20

volumes:
  files:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ./files
  db-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ./data

networks:
  docker_net:
    external: true
